# BEGIN_KITTY_THEME
# OneDark-Pro
include current-theme.conf
# END_KITTY_THEME

enable_audio_bell no
font_size 14
repaint_delay 1
confirm_os_window_close 0 
paste_actions no-op
window_padding_width 0
# window_padding_width 8 12
# kitty_mod ctrl+a
# scrollback_pager vim -u NONE -
#   \ -c 'w! /tmp/kitty_scrollback' 
#   \ -c 'term ++curwin cat /tmp/kitty_scrollback'
#   \ -c "set clipboard=unnamed"
#   \ -c "hi Normal ctermbg=235"
#   \ -c "nnoremap Y y$"
#   \ -c "tnoremap i ZQ"


hide_window_decorations titlebar-only
macos_show_window_title_in none

# map kitty_mod+i show_scrollback
# BEGIN_KITTY_FONTS
font_family      family="Menlo"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#
background_opacity 0.80
dynamic_background_opacity yes
background_blur 10
modify_font cell_height 115%

# tab_bar_style hidden
map ctrl+a>$ set_tab_title " "
enabled_layouts splits:split_axis=horizontal,stack,grid

# Layout
map ctrl+a>space next_layout
map ctrl+a>z toggle_layout stack
map ctrl+a>c launch --type=tab --cwd=current
map ctrl+a>t new_tab !neighbor
map ctrl+a>s launch --location=vsplit


# Movement
map ctrl+a>h previous_window
map ctrl+a>l next_window
map ctrl+a>j neighboring_window down
map ctrl+a>k neighboring_window up
map ctrl+a>shift+[ move_window left
map ctrl+a>shift+] move_window right

map ctrl+a>p previous_tab
map ctrl+a>n next_tab
map ctrl+a>shift+, move_tab_backward
map ctrl+a>shift+. move_tab_forward

map ctrl+a>x close_window
map ctrl+a>q close_tab


map cmd+h previous_tab
map cmd+l next_tab
map cmd+; launch --type=tab --cwd=current
map cmd+a>c launch --type=tab --cwd=current
map cmd+a>x close_window
map cmd+u goto_tab 1
map cmd+i goto_tab 2
map cmd+o goto_tab 3
map cmd+p goto_tab 4
map cmd+y goto_tab 5
map cmd+m no_op


map cmd+a>1 goto_tab 1
map cmd+a>2 goto_tab 2
map cmd+a>3 goto_tab 3
map cmd+a>4 goto_tab 4
map cmd+a>5 goto_tab 5
map cmd+a>6 goto_tab 6
map cmd+a>7 goto_tab 7
map cmd+a>8 goto_tab 8
map cmd+a>9 goto_tab 9
map cmd+a>0 goto_tab 1

map ctrl+a>1 goto_tab 1
map ctrl+a>2 goto_tab 2
map ctrl+a>3 goto_tab 3
map ctrl+a>4 goto_tab 4
map ctrl+a>5 goto_tab 5
map ctrl+a>6 goto_tab 6
map ctrl+a>7 goto_tab 7
map ctrl+a>8 goto_tab 8
map ctrl+a>9 goto_tab 9
map ctrl+a>0 goto_tab 1

#Tab bar
tab_bar_min_tabs 1
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {index}
tab_bar_margin_height 3.0 0.0
#Ends Tab bar


# Allow programs to control Kitty
allow_remote_control yes
listen_on unix:/tmp/mykitty

